spring:
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:h2:mem:testdb
#    url: jdbc:h2:mem:testdb

    # 切换为mysql
    platform: MYSQL
    username: root
    password:
    url: jdbc:mysql://localhost/coffeebucks?useSSL=false
    schema: classpath:schema.sql
    data: classpath:data.sql
    initializationMode: always
  jpa:
    hibernate:
      # 不启用hibernate ddl-auto
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6300
management:
  health:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    author: Kelvin Chen
    encoding: @project.build.sourceEncoding@
