spring:
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:h2:mem:testdb
#    url: jdbc:h2:mem:testdb

    # 切换为mysql
    platform: MYSQL
    username: root
    password:
    url: jdbc:mysql://localhost/coffeebucks?useSSL=false
    schema: classpath:schema.sql
    data: classpath:data.sql
    initializationMode: always
  jpa:
    hibernate:
      # 启动应用create表, 关闭应用drop表
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6300
